apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: db
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: db
    project: workshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ $.Release.Namespace }}
  labels:
    app: db
    project: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        project: workshop
    spec:
      containers:
        - name: db
          image: {{ $.Values.db.image }}
          imagePullPolicy: {{ $.Values.php.imagePullPolicy }}
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
