php:
  # Don't pull ever because it should be retrieved from the docker daemon which we populated from our host machine
  imagePullPolicy: Never
  image: workshop-php

cronjobs:
  clearMessages:
    enabled: false

db:
  imagePullPolicy: Never
  image: workshop-db

nginx:
  # Don't pull ever because it should be retrieved from the docker daemon which we populated from our host machine
  imagePullPolicy: Never
  image: workshop-nginx
  ingress:
    host: workshop.test
    port: 80
